name: Tournament
version: ${project.version}
main: me.devik.tournament.Tournament
api-version: 1.17
authors: [ Devik ]
description: Plugin which will start a Tournament and you can set a time
commands:
  tournament:
    description: Set a time for start a tournament
    usage: /<command>
