name: Test_GUI
version: ${project.version}
main: me.devik.test_gui.Test_GUI
api-version: 1.17
authors: [ Devik ]
description: Testing GUI
commands:
  gui:
    description: Test GUI
    usage: /<command>
